import"./assets/styles-DAE99nJD.js";import{a as n}from"./assets/vendor-2s9xPmg-.js";const $="https://dummyjson.com",a={CATEGORIES:"products/category-list",PRODUCTS:"products",CATEGORY:"products/category/"},g=12,r={QUERY:"",PAGE:1},s={categoriesList:document.querySelector("ul.categories"),productsList:document.querySelector("ul.products"),notFoundBlock:document.querySelector("div.not-found"),modal:document.querySelector("div.modal"),modalProduct:document.querySelector("div.modal-product"),closeModalBtn:document.querySelector(".modal__close-btn")};function L(){s.productsList.innerHTML=""}function P(t){const o=document.querySelector(".categories__btn--active");o&&o.classList.remove("categories__btn--active"),t.classList.add("categories__btn--active")}function v(){s.notFoundBlock.classList.add("not-found--visible")}function b(){s.notFoundBlock.classList.remove("not-found--visible")}function k(){s.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",window.addEventListener("keydown",y),s.modal.addEventListener("click",f)}function _(){s.modal.classList.remove("modal--is-open"),document.body.style.overflow="",window.removeEventListener("keydown",y),s.modal.removeEventListener("click",f)}function y(t){t.code==="Escape"&&_()}function f(t){t.target===s.modal&&_()}n.defaults.baseURL=$;async function A(){return(await n.get(a.CATEGORIES)).data}async function E(t){const o=(t-1)*12;return(await n.get(`${a.PRODUCTS}?limit=${g}&skip=${o}`)).data}async function w(t,o){const c=(o-1)*12;return(await n.get(`${a.CATEGORY}${t}?limit=${g}&skip=${c}`)).data}async function C(t){return(await n.get(`${a.PRODUCTS}/${t}`)).data}function h(t){const c=["All",...t].map(e=>`<li class="categories__item">
      <button class="categories__btn" type="button">${e}</button>
    </li>`).join("");s.categoriesList.innerHTML=c}function m(t){const o=t.map(({id:c,thumbnail:e,description:i,title:d,brand:l,category:u,price:p})=>`<li class="products__item" data-id="${c}">
    <img class="products__image" src="${e}" alt="${i}"/>
    <p class="products__title">${d}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: </span>${l||"no brand"}</p>
    <p class="products__category">Category: ${u}</p>
    <p class="products__price">Price: ${p}$</p>
 </li>`).join("");s.productsList.insertAdjacentHTML("beforeend",o)}function S(t){const{images:o,title:c,description:e,tags:i,price:d,shippingInformation:l,returnPolicy:u}=t,p=`<img class="modal-product__img" src="${o[0]}" alt="${c}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${c}</p>
        <ul class="modal-product__tags">${i}</ul>
        <p class="modal-product__description">${e}</p>
        <p class="modal-product__shipping-information">Shipping: ${l}</p>
        <p class="modal-product__return-policy">Return Policy: ${u}</p>
        <p class="modal-product__price">Price: ${d}$</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;s.modalProduct.innerHTML=p}async function G(){try{const t=await A();h(t)}catch(t){console.error(`Get categories error: ${t}`)}try{const{products:t}=await E(r.PAGE);m(t)}catch(t){console.error(`Get products error: ${t}`)}}async function R(t){const o=t.target.closest(".categories__btn");if(!o)return;L(),P(o),b(),r.PAGE=1;const c=o.textContent;if(c==="All")try{const{products:e}=await E(r.PAGE);m(e)}catch(e){console.error(`Get products error: ${e}`)}else{r.QUERY=c;try{const{products:e}=await w(r.QUERY,r.PAGE);e.length===0?v():m(e)}catch(e){console.error(`Get products error: ${e}`)}}}async function T(t){const o=t.target.closest("li.products__item");if(!o)return;const c=o.dataset.id;try{const e=await C(c);S(e),k()}catch(e){console.error(`Get product error: ${e}`)}}document.addEventListener("DOMContentLoaded",G);s.categoriesList.addEventListener("click",R);s.productsList.addEventListener("click",T);s.closeModalBtn.addEventListener("click",_);
//# sourceMappingURL=index.js.map
