export const refs = {
  categoriesList: document.querySelector('ul.categories'),
  productsList: document.querySelector('ul.products'),
  notFoundBlock: document.querySelector('div.not-found'),
  modal: document.querySelector('div.modal'),
  modalProduct: document.querySelector('div.modal-product'),
  closeModalBtn: document.querySelector('.modal__close-btn'),
  loadMoreBtn: document.querySelector('.load-more-btn'),
  searchForm: document.querySelector('.search-form'),
  clearSearchFormBtn: document.querySelector('.search-form__btn-clear'),
  addToCardBtn: document.querySelector('.modal-product__btn--cart'),
  addToWishlistBtn: document.querySelector('.modal-product__btn--wishlist'),
  cartCounter: document.querySelector('[data-cart-count]'),
  wishlistCounter: document.querySelector('[data-wishlist-count]'),
  themeToggleBtn: document.querySelector('.theme-toggle-btn'),
};
